export const MACHINES_DATA = [
  {
    level: 1,
    name: "Machine 1 — Free Starter Machine",
    entryFee: 0,
    requiredRef: 0,
    requiredDep: 0,
    socialRequired: false,
    engines: [
      { id: 1, name: "Engine 1", price: 0, rate: 5, isFree: true },
      { id: 2, name: "Engine 2", price: 20, rate: 5 },
      { id: 3, name: "Engine 3", price: 40, rate: 5 },
      { id: 4, name: "Engine 4", price: 60, rate: 5 },
      { id: 5, name: "Engine 5", price: 80, rate: 5 },
    ],
  },
  {
    level: 2,
    name: "Machine 2 — Social Unlock Machine",
    entryFee: 500,
    requiredRef: 0,
    requiredDep: 0,
    socialRequired: true,
    engines: [
      { id: 6, name: "Engine 1", price: 300, rate: 10 },
      { id: 7, name: "Engine 2", price: 600, rate: 10 },
      { id: 8, name: "Engine 3", price: 800, rate: 10 },
      { id: 9, name: "Engine 4", price: 1000, rate: 10 },
      { id: 10, name: "Engine 5", price: 1200, rate: 10 },
    ],
  },
  {
    level: 3,
    name: "Machine 3 — Referral Unlock Machine",
    entryFee: 500,
    requiredRef: 3,
    requiredDep: 0,
    socialRequired: false,
    engines: [
      { id: 11, name: "Engine 1", price: 500, rate: 15 },
      { id: 12, name: "Engine 2", price: 1000, rate: 15 },
      { id: 13, name: "Engine 3", price: 1500, rate: 15 },
      { id: 14, name: "Engine 4", price: 2000, rate: 15 },
      { id: 15, name: "Engine 5", price: 2500, rate: 15 },
    ],
  },
  {
    level: 4,
    name: "Machine 4 — Deposit Starter Machine",
    entryFee: 500,
    requiredRef: 0,
    requiredDep: 20,
    socialRequired: false,
    engines: [
      { id: 16, name: "Engine 1", price: 700, rate: 20 },
      { id: 17, name: "Engine 2", price: 1400, rate: 20 },
      { id: 18, name: "Engine 3", price: 2100, rate: 20 },
      { id: 19, name: "Engine 4", price: 2800, rate: 20 },
      { id: 20, name: "Engine 5", price: 3500, rate: 20 },
    ],
  },
  {
    level: 5,
    name: "Machine 5 — Premium Mining Machine",
    entryFee: 500,
    requiredRef: 0,
    requiredDep: 50,
    socialRequired: false,
    engines: [
      { id: 21, name: "Engine 1", price: 3000, rate: 50 },
      { id: 22, name: "Engine 2", price: 5000, rate: 50 },
      { id: 23, name: "Engine 3", price: 7000, rate: 50 },
    ],
  },
];